### ISSUE TITLE
配置测试aws 账户的

### ISSUE THREAD

**Issue by fenglinnorway** [fenglinnorway/room-booking#4]
登陆到aws账户
https://541900922188.signin.aws.amazon.com/console
user s3_kaiqiang
pass:&8ybD1}+qp&$
登陆后要配置自己的mfa， 可以用authy desktop 做为虚拟mfa。
如果mac上不能装，可以下载安装手机版本。
登陆后点击右上角用户名下拉菜单
点击 my security credentials
在页面选择assign mfa device。
在popup里选择virtual mfa device
加下来的页面里需要你点击show security key然后把产生的字串添加到authy desktop 里
然后把authy desktop 生成的code 添加两个在mfa code 1， mfa code 2里。
这样你就建立了自己的mfa设备和账户的关联。

打开一个terminal
安装aws 命令行 查看https://docs.aws.amazon.com/cli/latest/userguide/install-macos.html
安装vaulted 

brew install vaulted

建立一个profile

vaulted add s3_kaiqiang

按a 配置亚马逊

press k to enter access key id, and copy <key id> the prumpt

enter access key: copy <key> the prumpt

这个时候vaulted 会自动检索是否有mfa 设备， 可以用检索出来的， 如果没有， 按m
填写如下信息
你的mfa设备的arn

最后q 退出保存

如何使用， 每次运行spring boot api application之前。在命令行写 
vaulted shell s3_kaiqiang
填你的passport， 填你的fma 设备提供的数字
测试如下命令

然后就可以运行 spring-boot API application了 ， 但是只能命令行运行

测试。如下命令
上传
aws s3 cp <文件名> s3://mediafile-repository-5419-0092-2188/<文件名> 

下载
aws s3 cp s3://mediafile-repository-5419-0092-2188/<文件名>  <文件名>

**Comment by Zhangkaiqiang** [comment]
i finished

**Comment by fenglinnorway** [comment]
good

________________________________

**Comment by fenglinnorway** [comment]
then mark it as closed.

________________________________
